import asyncio
import uuid
from typing import AsyncGenerator, List

from google import genai
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from tenacity import (
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

from src.core.config import settings
from src.models.chunks import DocumentChunk
from src.models.document import Document
from src.services.embedding_service import EmbeddingService
from src.utils.chunking import chunk_text


# Auto-retry logic for 503 Server Errors (High Demand Spikes)
@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=2, max=6),
    retry=retry_if_exception_type(genai.errors.ServerError),
    reraise=True,
)
def _call_gemini_stream(client: genai.Client, prompt: str):
    return client.models.generate_content_stream(
        model="models/gemini-3.6-flash",
        contents=prompt,
    )


class RAGService:
    def __init__(self, db_session: AsyncSession):
        self.db_session = db_session
        self.embedding_service = EmbeddingService()
        self.ai_client = genai.Client(api_key=settings.GOOGLE_API_KEY)

    async def process_and_store_document(
        self, document_id: uuid.UUID, text: str
    ) -> List[DocumentChunk]:
        raw_chunks = chunk_text(text)
        if not raw_chunks:
            return []

        loop = asyncio.get_running_loop()
        embeddings = await loop.run_in_executor(
            None, self.embedding_service.get_embeddings_batch, raw_chunks
        )

        chunk_objects = [
            DocumentChunk(document_id=document_id, chunk_text=piece, embedding=vector)
            for piece, vector in zip(raw_chunks, embeddings)
        ]

        self.db_session.add_all(chunk_objects)
        await self.db_session.commit()

        return chunk_objects

    async def search_similar_chunks(
        self, query: str, org_id: uuid.UUID, limit: int = 3
    ) -> List[DocumentChunk]:
        loop = asyncio.get_running_loop()
        query_embedding = await loop.run_in_executor(
            None, self.embedding_service.get_embeddings, query
        )

        stmt = (
            select(DocumentChunk)
            .join(Document, DocumentChunk.document_id == Document.id)
            .where(Document.organization_id == org_id)
            .order_by(DocumentChunk.embedding.cosine_distance(query_embedding))
            .limit(limit)
        )
        result = await self.db_session.execute(stmt)
        return list(result.scalars().all())

    async def answer_query(self, query: str, org_id: uuid.UUID) -> str:
        similar_chunks = await self.search_similar_chunks(
            query=query, org_id=org_id, limit=3
        )
        if not similar_chunks:
            return "No relevant information found in documents."

        context = "\n\n".join([str(c.chunk_text) for c in similar_chunks])
        prompt = f"""
You are an AI assistant answering questions based on the provided context.

Context:
{context}

User Question: {query}

Answer:
"""
        loop = asyncio.get_running_loop()
        response = await loop.run_in_executor(
            None,
            lambda: self.ai_client.models.generate_content(
                model="models/gemini-3.6-flash",
                contents=prompt,
            ),
        )

        return response.text or "No response text generated by the model."

    async def answer_query_stream(
        self, query: str, org_id: uuid.UUID
    ) -> AsyncGenerator[str, None]:
        similar_chunks = await self.search_similar_chunks(
            query=query, org_id=org_id, limit=3
        )
        if not similar_chunks:
            yield "No relevant information found in documents."
            return

        context = "\n\n".join([str(c.chunk_text) for c in similar_chunks])
        prompt = f"""
You are an AI assistant answering questions based on the provided context.

Context:
{context}

User Question: {query}

Answer:
"""
        loop = asyncio.get_running_loop()

        try:
            response_stream = await loop.run_in_executor(
                None, lambda: _call_gemini_stream(self.ai_client, prompt)
            )

            for chunk in response_stream:
                if chunk.text:
                    yield chunk.text
        except genai.errors.ServerError:
            yield "\n[Notice: AI server traffic high. Please re-send request.]"
