"""add_extracted_content_to_document

Revision ID: <KEEP_THE_GENERATED_HASH_HERE>
Revises: fb7b49ddfb41
Create Date: 2026-07-22

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# Revision identifiers generated by Alembic (do not change revision or down_revision hash)
revision: str = "70fbb5138a2e"
down_revision: Union[str, None] = "fb7b49ddfb41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ➕ Pure DB ko touch kiye bina sirf extracted_content column add karo
    op.add_column("document", sa.Column("extracted_content", sa.Text(), nullable=True))


def downgrade() -> None:
    # ➖ Rollback logic
    op.drop_column("document", "extracted_content")
