"""add_organization_and_membership_tables

Revision ID: fb7b49ddfb41
Revises: 3c929d0fcb1f
Create Date: 2026-07-16 00:49:54.500051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7b49ddfb41'
down_revision: Union[str, Sequence[str], None] = '3c929d0fcb1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
